apiVersion: apps/v1
kind: Deployment
metadata:
  name: attacker
  namespace: kubeflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attacker
  template:
    metadata:
      labels:
        app: attacker
    spec:
      containers:
        - name: attacker
          image: gkorod/attacker:v1.0
          imagePullPolicy: Always
          env:
            - name: DATA_URL
              value: "http://147.102.19.170:4422/download/classifier"
            - name: MODEL_PATH
              value: "/trained_models/model_a.pth"
            - name: BATCH_SIZE
              value: "64"
            - name: EPOCHS
              value: "10"
            - name: LR
              value: "0.001"
          volumeMounts:
            - name: trained-models-volume
              mountPath: /trained_models

      volumes:
        - name: trained-models-volume
          persistentVolumeClaim:
            claimName: trained-models
