apiVersion: apps/v1
kind: Deployment
metadata:
  name: attacker
  namespace: kubeflow
  labels:
    app: attacker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attacker
  template:
    metadata:
      labels:
        app: attacker
    spec:
      containers:
        - name: attacker
          image: gkorod/attacker:v1.0
          imagePullPolicy: Always
          env:
            - name: DATA_URL
              value: 'http://147.102.19.170:4422/download/classifier'
            - name: MODEL_PATH
              value: '/trained_models/model_a.pth'
            - name: BATCH_SIZE
              value: '64'
            - name: EPOCHS
              value: '10'
            - name: LR
              value: '0.001'
          volumeMounts:
            - name: host-file
              mountPath: /trained_models/model_a.pth

      volumes:
        - name: host-file
          hostPath:
            path: /home/gkorod/Downloads/model_a.pth   # file on the node
            type: File
